# Site settings
title: Get Well Messages
email: hello@getwellmessages.net
description: > # this means to ignore newlines until "baseurl:"
  If you're struggling with what to say in a get well card our range of messages, quotes, poems and more will help you write the best get well message.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://getwellmessages.net" # the base hostname & protocol for your site
twitter_username: getwellmessages
github_username:  jekyll

# Build settings
markdown: kramdown

permalink: '/:title/'
paginate_path: '/page:num/'
paginate: 4

author:
  name:         'Admin'
  url:          https://www.getwellmessages.net
  email:        hello@getwellmessages.net

categories: [messages, quotes, poems, prayers, funny, faq]

google_adsense: ca-pub-2642906032724935