# Site settings
title: getwellmessages.net
email: hello@getwellmessages.net
description: > # this means to ignore newlines until "baseurl:"
  A Crotchey Blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://getwellmessages.net" # the base hostname & protocol for your site
twitter_username: getwellmessages
github_username:  jekyll

# Build settings
markdown: kramdown

permalink: '/:title/'
paginate_path: '/page:num/'
paginate: 4

author:
  name:         'Admin'
  url:          https://www.getwellmessages.net
  email:        hello@getwellmessages.net
