# Site settings
title: Crotchet.net
email: crotchet@crotchet.net
description: > # this means to ignore newlines until "baseurl:"
  A Crotchey Blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.crotchet.net" # the base hostname & protocol for your site
twitter_username: crotchetnet
github_username:  jekyll

# Build settings
markdown: kramdown

permalink: '/:title/'
paginate_path: '/page:num/'
paginate: 4

author:
  name:         'Andy'
  url:          http://www.crotchet.net
  email:        crotchet@crotchet.net
